### ISSUE TITLE
More Attractive To Viewers.

### ISSUE THREAD

**Issue by zachlehman99** [jmorris1990/finalproject#19]
The idea of centering the Canvas on the screen and maybe of made the board and html a different color. But you should center the Canvas so it is presented better to the customer

https://github.com/jmorris1990/finalproject/blob/688c9002c9edc9da2c003772bd4ee7bf2b257338/styles.css#L1-L6

**Comment by briangx92** [comment]
i did that prior but it bugged out with canvas

**Comment by briangx92** [comment]
I'll try to figure it out though
